# Generated by Django 2.0.4 on 2018-07-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_drawing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
