# Generated by Django 2.0.4 on 2018-07-05 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_drawing_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='is_main',
            new_name='is_pinned',
        ),
    ]
